### ISSUE TITLE
v1.1.4 shows an error stating that the step value should not be 0 even when it is not 0

### ISSUE THREAD

**Issue by rickyv3** [mendixlabs/range-slider#10]
Hi @Andries-Smit ,

v1.1.4 shows an error stating that the step value should not be 0 even when it is not, e.g. in this case it is 10. I've attached screenshots. 

![stepvalue1](https://user-images.githubusercontent.com/13573078/37969918-a8656f7a-3197-11e8-9bcb-5b7c50e787e8.png)
![stepvalue2](https://user-images.githubusercontent.com/13573078/37969919-a87ef4ea-3197-11e8-9182-9332d877b86d.png)

Best,
Ricky

**Comment by akileng56** [comment]
Hi @rickyv3 , The Step value can only be used if the Step attribute is not set. Priority is given to the step attribute.
![image](https://user-images.githubusercontent.com/20700222/37970799-07db0b46-31dd-11e8-9279-a50c6923d950.png)

**Comment by Andries-Smit** [comment]
@rickyv3 What do you like to store in the attribute "Activuty.LaborerRTHoursWorked" ? 
The `Step` value and attribute are not for the displaying values. (The actual values are to be set in Data Source, https://github.com/mendixlabs/range-slider/blob/master/assets/Datasource.PNG) `Lower bound attribute` and `Upper bound attribute` 

While the `Step` indicates the gaps between each selectable point on the slider.

**Comment by rickyv3** [comment]
@Andries-Smit sorry that was my confusion, I actually need to store the selected value of the range. I believe there was an older version of the range slider that allowed me to set a max / min and store a single value attribute.

**Comment by Andries-Smit** [comment]
There are 2 types of slider widget:
 * Slider => single attribute https://github.com/mendixlabs/slider/blob/master/assets/usage.PNG
 * Range Slider => two attributes, Upper bound value, Lower bound value. https://github.com/mendixlabs/range-slider/blob/master/assets/Inaction.PNG

The select range is set with the `Maximum attribute` and `Minimum attribute`

**Comment by rickyv3** [comment]
Bingo, thank you!

**Comment by Andries-Smit** [comment]
Lets see if we can improve in the documentation.
Thanks for reporting the issue, as it was both in the Slider and Range slider. We will fix the 0 Step issue in the Slider shortly.

Cheers!
