### ISSUE TITLE
Error message doesn't disappear when error is resolved

### ISSUE THREAD

**Issue by FredPetrignani** [mendixlabs/range-slider#3]
![rangeslider](https://user-images.githubusercontent.com/26164626/27134140-ed9160fe-5114-11e7-86af-2c3185ea200d.PNG)

This error message appeared when I first ran the app with the range slider. I corrected the error by changing the default value of the upper bound attribute in the domein model. However, the error message doesn't go away. Does the widget store the value somewhere? If so, how to clear?

**Comment by Andries-Smit** [comment]
Hi Fred, think you solved the issue. When changing the domain model default value, you do not change the value of of the data that is already in the system.

**Comment by FredPetrignani** [comment]
That’s right, Andries. Tx!

Met vriendelijke groet,

Frederic Petrignani | Business Engineer | www.appronto.nl<http://www.appronto.nl/>
T: +31 6 53457168 | M: frederic.petrignani@appronto.nl<mailto:frederic.petrignani@appronto.nl>
Vind ons op LinkedIn<https://www.linkedin.com/company/appronto> | Twitter<https://twitter.com/approntonl> | Facebook<https://www.facebook.com/Appronto> / Lees het laatste nieuws over Appronto en Mendix<http://www.appronto.nl/nieuws/>

[Appronto BV]


Van: Andries Smit [mailto:notifications@github.com]
Verzonden: maandag 19 juni 2017 09:32
Aan: mendixlabs/range-slider <range-slider@noreply.github.com>
CC: Frederic Petrignani <Frederic.Petrignani@appronto.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [mendixlabs/range-slider] Error message doesn't disappear when error is resolved (#3)


Hi Fred, think you solved the issue. When changing the domain model default value, you do not change the value of of the data that is already in the system.
