### ISSUE TITLE
Seems broken in modeler 7.10.0

### ISSUE THREAD

**Issue by lrporder** [mendixlabs/range-slider#6]
Widget seems broken in latest modeler 7.10.0. No warnings in the modeler or log or anything, just a red danger alert box on screen with "An error occurred in a "com.mendix.widget.custom.RangeSlider.RangeSlider" widget. Check updates for the widget in the Mendix App Store or contact the widget developer."

**Comment by akileng56** [comment]
Thank you for reporting this issue. We have tested the Range slider on 7.10.0 and it works fine.
We expect the issue to be related to the configurations. 
Could you please send a screenshot of your widget configurations so we can try to reproduce the issue?
Or even better send us a sample project.

**Comment by lrporder** [comment]
Thanks for your reply. I couldn't break the widget in a sample project in 7.10.0. It just works, with virtually the same setup (four integer attributes, non-persistable object, with on-change microflow). 
In our own project however it remained unwilling to recover from the update, so I just deleted it and downloaded the widget again. Now it works. Not sure what happened there. But I did see now we had version 1.1.0. I already checked if we had the latest version, but when the app store says 'Published: 8/2/2017' that apparently doesn't apply to the mentioned latest version. Anyway, version 1.1.2 works. So either version 1.1.0 doesn't work in 7.10, or an update from 7.9 to 7.10 breaks the widget. But for us it works now, so you can mark this issue as solved. Thank you.

**Comment by Andries-Smit** [comment]
Thanks you. Will close the issue.
